esphome:
  name: ha_backyard_motion
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout
  includes:
    - sb1_uart.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

debug:
logger:
  level: DEBUG
  hardware_uart: UART1
ota:

uart:
  - tx_pin: 1
    rx_pin: 3
    baud_rate: 9600
    id: uart0

binary_sensor:
  - platform: template
    id: motion
    name: "Backyard motion"
    device_class: motion
    lambda: "return {};"

custom_component:
  - id: sb1_uart
    lambda: |-
      auto component = new SB1UARTComponent(id(uart0), id(motion));
      return {component};

sensor:
  - platform: adc
    name: "Backyard motion Battery"
    pin: VCC

