esphome:
  name: ha_basement_door
  platform: ESP8266
  board: esp01_1m
  arduino_version: 2.5.1
  board_flash_mode: dout
  build_path: .build
  includes:
    - sb1_uart.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

debug:
logger:
  level: DEBUG
  hardware_uart: UART1
ota:

uart:
  - tx_pin: 1
    rx_pin: 3
    baud_rate: 9600
    id: uart0

binary_sensor:
  - platform: template
    id: door
    name: "Basement Door"
    device_class: door
    lambda: "return {};"

custom_component:
  - id: sb1_uart
    lambda: |-
      auto component = new SB1UARTComponent(id(uart0), id(door));
      return {component};

sensor:
  - platform: adc
    name: "Basement Door Battery"
    pin: VCC

