esphome:
  name: ha_bedroom_ble_bridge
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

debug:
logger:
  level: DEBUG
ota:

esp32_ble_tracker:

sensor:
  - platform: ble_rssi
    mac_address: !secret mac_cat_hygrometer
    name: "Cat Bedroom RSSI"

  - platform: xiaomi_lywsdcgq
    mac_address: !secret mac_bedroom_hygrometer
    temperature:
      name: "Bedroom Temperature"
    humidity:
      name: "Bedroom Humidity"
    battery_level:
      name: "Bedroom Battery Level"

  - platform: xiaomi_lywsdcgq
    mac_address: !secret mac_ines_room_hygrometer
    temperature:
      name: "Inês's room Temperature"
    humidity:
      name: "Inês's room Humidity"
    battery_level:
      name: "Inês's room Battery Level"
