esphome:
  name: ha_living_room_entryway_lamp
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

debug:
logger:
  level: DEBUG
ota:

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - light.toggle: lamp

output:
  - platform: gpio
    id: relay
    pin: GPIO12

light:
  - platform: binary
    id: lamp
    name: "Living Room Entryway Lamp"
    output: relay
