esphome:
  name: ha_living_room_ble_bridge
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

debug:
logger:
  level: DEBUG
ota:

esp32_ble_tracker:

sensor:
  - platform: ble_rssi
    mac_address: !secret mac_cat_trackr
    name: "Cat Living Room RSSI"

  - platform: xiaomi_hhccjcy01
    mac_address: !secret mac_citrus_hystrix
    temperature:
      name: "Citrus Hystrix Temperature"
    moisture:
      name: "Citrus Hystrix Moisture"
    illuminance:
      name: "Citrus Hystrix Illuminance"
    conductivity:
      name: "Citrus Hystrix Conductivity"
    battery_level:
      name: "Citrus Hystrix Battery Level"

  - platform: xiaomi_hhccjcy01
    mac_address: !secret mac_ficus_benjamina
    temperature:
      name: "Ficus Benjamina Temperature"
    moisture:
      name: "Ficus Benjamina Moisture"
    illuminance:
      name: "Ficus Benjamina Illuminance"
    conductivity:
      name: "Ficus Benjamina Conductivity"
    battery_level:
      name: "Ficus Benjamina Battery Level"

  - platform: xiaomi_hhccjcy01
    mac_address: !secret mac_fiddle_leaf
    temperature:
      name: "Fiddle Leaf Temperature"
    moisture:
      name: "Fiddle Leaf Moisture"
    illuminance:
      name: "Fiddle Leaf Illuminance"
    conductivity:
      name: "Fiddle Leaf Conductivity"
    battery_level:
      name: "Fiddle Leaf Battery Level"

  - platform: xiaomi_hhccjcy01
    mac_address: !secret mac_grass
    temperature:
      name: "Grass Temperature"
    moisture:
      name: "Grass Moisture"
    illuminance:
      name: "Grass Illuminance"
    conductivity:
      name: "Grass Conductivity"
    battery_level:
      name: "Grass Battery Level"

  - platform: xiaomi_hhccjcy01
    mac_address: !secret mac_monstera_deliciosa
    temperature:
      name: "Monstera Deliciosa Temperature"
    moisture:
      name: "Monstera Deliciosa Moisture"
    illuminance:
      name: "Monstera Deliciosa Illuminance"
    conductivity:
      name: "Monstera Deliciosa Conductivity"
    battery_level:
      name: "Monstera Deliciosa Battery Level"

  - platform: xiaomi_lywsdcgq
    mac_address: !secret mac_kitchen_hygrometer
    temperature:
      name: "Kitchen Temperature"
    humidity:
      name: "Kitchen Humidity"
    battery_level:
      name: "Kitchen Battery Level"
