esphome:
  name: ha_solar_webpage
  platform: ESP8266
  board: esp01_1m

debug:
logger:
  level: DEBUG
ota:

wifi:
  password: !secret wifi_password
  ssid: !secret wifi_ssid
  domain: !secret wifi_domain
  ap:
    ssid: "Solar Webpage"
    password: !secret wifi_ap_password

captive_portal:

web_server:
  port: 80

sensor:
  - platform: adc
    id: battery_voltage
    name: "Battery Voltage"
    pin: A0
    unit_of_measurement: "V"
    filters:
      # Take voltage divider into account (r1 = 10k; r2 = 2k)
      - lambda: return x * (10 + 2) / 2;

  - platform: template
    id: battery_percentage
    name: "Battery Percentage"
    unit_of_measurement: "%"
    lambda: |-
      return clamp(((id(battery_voltage).state - 3.7) / (4.3 - 3.7)) * 100, 0, 100);

  - platform: uptime
    name: Uptime
