esphome:
  name: ha_water_heater
  platform: ESP8266
  board: nodemcuv2
  includes:
    - vbusdecoder_uart.h
    - VBUSDecoder.h
    - VBUSDecoder.cpp

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

debug:
logger:
  level: DEBUG
  hardware_uart: UART1
ota:

uart:
  - rx_pin: D7
    baud_rate: 9600
    id: uart0

sensor:
  - platform: template
    id: collector_temperature
    name: "Water Heater Collector Temperature"
    lambda: "return {};"

  - platform: template
    id: tank_temperature
    name: "Water Heater Tank Temperature"
    lambda: "return {};"

custom_component:
  - id: vbus_decoder_uart
    lambda: |-
      auto component = new VBUSDecoderUARTComponent(id(uart0), id(collector_temperature), id(tank_temperature));
      return {component};
